---
# tasks file for duplicati_bitrix_env
- name: Install yum epel-release
  yum:
    name: epel-release
    state: latest
    update_cache: yes

- name: Install Duplicati
  yum:
    name: https://github.com/duplicati/duplicati/releases/download/v2.0.4.23-2.0.4.23_beta_2019-07-14/duplicati-2.0.4.23-2.0.4.23_beta_20190714.noarch.rpm
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  notify:
    - Install cert-sync
    - Start Duplicati and Enable it on the every boot

- name: Create systemd/system/duplicati.service
  copy:
    src: duplicati.service
    dest: /etc/systemd/system/duplicati.service
  notify:
    - Start Duplicati and Enable it on the every boot
    - Install cert-sync

- name: Configurate /etc/nginx/bx/site_avaliable/admin.bitrix.conf
  copy:
    src: admin.bitrix.conf
    dest: /etc/nginx/bx/site_avaliable/admin.conf
  notify:
    - nginx_restart

- name: Create a symbolic link
  file:
    src: /etc/nginx/bx/site_avaliable/admin.conf
    dest: /etc/nginx/bx/site_enabled/admin.conf
    state: link
  notify:
    - nginx_restart

- name: Insert a rule in the iptables
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "8000"
    jump: ACCEPT
    action: insert
  notify:
    - save iptables